# Tensors

In [1]:
import torch
import numpy as np

In [2]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

The code below creates a tensor that retains the shape and datatype of the original tensor supplied.

In [4]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 



However, to override the datatype:

In [5]:
x_rand = torch.rand_like(x_data,dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

Random Tensor: 
 tensor([[0.6517, 0.1344],
        [0.2241, 0.5656]]) 



In [6]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

In [7]:
rand_tensor

tensor([[0.8753, 0.6061, 0.5613],
        [0.8554, 0.7610, 0.2031]])

In [8]:
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
zeros_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [13]:
rand_tensor.shape

torch.Size([2, 3])

In [11]:
rand_tensor.dtype

torch.float32

In [12]:
rand_tensor.device

device(type='cpu')

In [14]:
tensor = torch.rand((3,3,))

In [15]:
tensor

tensor([[0.9319, 0.1882, 0.7352],
        [0.7870, 0.2485, 0.7723],
        [0.6811, 0.6660, 0.7450]])

In [16]:
tensor[0]

tensor([0.9319, 0.1882, 0.7352])

In [17]:
tensor[:,0]

tensor([0.9319, 0.7870, 0.6811])

In [18]:
tensor[...,-1]

tensor([0.7352, 0.7723, 0.7450])

### Multiplying Tensors

In [19]:
y1 = tensor @ tensor.T

In [20]:
y1

tensor([[1.4443, 1.3480, 1.3077],
        [1.3480, 1.2776, 1.2768],
        [1.3077, 1.2768, 1.4624]])

In [21]:
y2 = tensor.matmul(tensor.T)

In [22]:
y2

tensor([[1.4443, 1.3480, 1.3077],
        [1.3480, 1.2776, 1.2768],
        [1.3077, 1.2768, 1.4624]])

In [23]:
y1==y2

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [24]:
z1 = tensor * tensor

In [25]:
z1

tensor([[0.8684, 0.0354, 0.5405],
        [0.6194, 0.0617, 0.5964],
        [0.4639, 0.4436, 0.5550]])

To convert single valued tensors to python float, we use:

In [26]:
add = z1.sum()

In [27]:
add

tensor(4.1843)

In [28]:
print(add.item(),type(add.item()))

4.1843156814575195 <class 'float'>


Adding a value to an entire tensor:

In [29]:
z1.add_(5)

tensor([[5.8684, 5.0354, 5.5405],
        [5.6194, 5.0617, 5.5964],
        [5.4639, 5.4436, 5.5550]])